name: Build and publish on GHCR

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-push:
    continue-on-error: true  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: 
        - linux/arm64
        - linux/amd64
        - linux/arm/v7
        - linux/ppc64le 
        - linux/s390x

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Build the image
        run: |
          docker buildx ls
          _ARCH="${{ matrix.platform }}"
          ARCH="${_ARCH//\//-}"
          docker buildx build \
            -f Dockerfile \
            --tag ghcr.io/albertogeniola/$ARCH-mikrotik-ovh-updater:latest \
            --push \
            --squash \
            --platform ${{ matrix.platform }} .